local mq = require("mq")
local PriorityQueue = require("utils.priorityqueue.priorityqueue")

mq.cmd("/mqclear")

local pq = PriorityQueue:new(200)
local pqToTestMultipleQueues = PriorityQueue:new(10)
assert(pq.maxSize == 200, "secondary queue reset maxsize of first queue")

pq:Print()
print("should have been empty...")
print()
assert(#pq.jobs == 0, "Queue should have been empty")

pq:InsertNewJob(3, "foo", 0, false)
pq:Print()
print("added foo")
print()
local newJob = pq:GetCurrentJob()
assert(#pq.jobs == 1, "Queue size should be 1")
assert(newJob == nil, "currentJob should still be nil")
---@type Job
newJob = pq.jobs[1]
newJob:IsVisible()
assert(newJob.command == "foo", "new job should be foo")
assert(newJob.IsVisible(newJob), "new job should be visible")
assert(newJob.priority == 3, "new job priority should be 3")
pqToTestMultipleQueues:Print()
assert(#pqToTestMultipleQueues.jobs == 0, "Secondary queue should not be altered")

pq:InsertNewJob(4, "bar", 0, false)
pq:Print()
print("added bar")
print()

pq:InsertNewJob(5, "zoo", 0, false)
pq:Print()
print("added zoo")
print()

pq:InsertNewJob(3, "bazzar", 3, false)
pq:Print()
print("added bazzar after foo with small timer")
print()

pq:InsertNewJob(1, "skip", 0, false)
pq:Print()
print("skip to front")
print()

pq:InsertNewJob(3, "foo", 0, true)
pq:Print()
print("tried to add duplicate foo, but was set to unique only")
print()

pq:InsertNewJob(3, "foo", 0, false)
pq:Print()
print("added duplicate foo")
print()

pq:SetNextJob()
assert(pqToTestMultipleQueues.currentJobKey == -1, "Secondary Queue should not be updating keys")
pqToTestMultipleQueues:InsertNewJob(1, "alt", 0, false)
pq:CompleteCurrentJob()
assert(#pqToTestMultipleQueues.jobs == 1, "completing job shouldn't impact alternate queue")
pq:Print()
print("completed current job")
print()

local key = pq.jobs[3].key
pq:CompleteJobByKey(key)
pq:Print()
print("completed job at index 3")
print()

pq:CompleteJobByKey(10)
pq:Print()
print("tried to complete job at index 10")
print()

pq:SetNextJob()
pq:CompleteCurrentJob()
pq:Print()
print("completed next job")
print()

pq:SetNextJob()
pq:CompleteCurrentJob()
pq:Print()
print("completed next job")
print()

mq.delay(1000)
pq:SetNextJob()
pq:CompleteCurrentJob()
pq:Print()
print("completed next job, delayed 1s")
print()

mq.delay(1000)
pq:SetNextJob()
pq:CompleteCurrentJob()
pq:Print()
print("completed next job, delayed 1s")
print()

mq.delay(1000)
pq:SetNextJob()
pq:CompleteCurrentJob()
pq:Print()
print("completed next job, delayed 1s")
print()

mq.delay(1000)
pq:SetNextJob()
pq:CompleteCurrentJob()
pq:Print()
print("completed next job, delayed 1s")
print()

pq:InsertNewJob(3, "foo", 0, false)
pq:Print()
print("added foo")
print()